# docker-compose.yml for embeddings-api

services:
  api:
    build: .
    image: embeddings_api
    command: ["uvicorn", "embedding_api:app", "--host=0.0.0.0", "--port=5681"]
    ports:
      - "5681:5681"  
